server:
  error:
    include-stacktrace: on_param

spring:
  profiles:
    active: dev

info:
  app: Spring Boot 2 Essentials By DevDojo
  website: https://devdojo.academy
  github: https://github.com/devdojobr/springboot2-essentials

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"